[versions]
changelog = "2.4.0"
intelliJPlatform = "2.9.0"
kotlin = "2.1.20"


[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
