[versions]
kotlin = "2.0.21"
intellijPlatform = "2.1.0"
changelog = "2.2.0"
junit = "5.11.0"
opentest4j = "1.3.0"

[libraries]
junit = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intellijPlatform" }
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
